add_newline = true
command_timeout = 200
format = "[$directory$git_branch$git_status]($style)$character"

palette = "rose-pine"

[palettes.rose-pine]
base = "#191724"
surface = "#1f1d2e"
overlay = "#26233a"
muted = "#6e6a86"
subtle = "#908caa"
text = "#e0def4"
love = "#eb6f92"
gold = "#f6c177"
rose = "#ebbcba"
pine = "#31748f"
foam = "#9ccfd8"
iris = "#c4a7e7"
highlight_low = "#21202e"
highlight_med = "#34303d"
highlight_high = "#524f67"

[character]
error_symbol = "[✗](bold love)"
success_symbol = "[❯](bold pine)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold pine"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
style = "foam"

[git_branch]
format = "[$branch]($style) "
style = "italic iris"

[git_status]
format     = '[$all_status]($style)'
style      = "iris"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""
