import = ["/home/johan/.config/alacritty/colors.toml", "/home/johan/.config/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

# [shell]
# program = "/bin/tmux"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.95
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 24

# [window.padding]
# x = 10 
# y = 10
